<a href="https://colab.research.google.com/github/joaop-n12/Machine_Learning/blob/main/atv_dia_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import seaborn as sns
import statsmodels.api as sm
from sklearn.preprocessing import PolynomialFeatures
import scipy.stats as stats
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv('/content/exercise_angles.csv')
df



Side  Shoulder_Angle  Elbow_Angle   Hip_Angle  Knee_Angle  Ankle_Angle  \
0      left       10.639208   174.466813  174.785143  179.848140   179.419276   
1      left       10.590342   174.428706  174.765042  179.775215   179.386147   
2      left       10.546746   174.489431  174.785790  179.660017   179.333710   
3      left       10.487682   174.614913  174.759542  179.614223   179.313926   
4      left       10.412107   174.758503  174.737721  179.570564   179.298805   
...     ...             ...          ...         ...         ...          ...   
31028  left       12.723974    81.226330  149.356832  154.358415   178.103121   
31029  left        9.080920    82.486551  148.100509  152.680540   178.625318   
31030  left        4.118076    85.164707  148.329461  152.458288   178.605852   
31031  left        0.558065    89.419330  146.742440  149.930600   179.604753   
31032  left        3.610121    89.992518  141.439189  144.633832   179.616705   

       Shoulder_Ground_Angle  Elbow_Ground_Angle  Hip_Ground_Angle  \
0                       90.0                90.0              90.0   
1                       90.0                90.0              90.0   
2                       90.0                90.0              90.0   
3                       90.0                90.0              90.0   
4                       90.0                90.0              90.0   
...                      ...                 ...               ...   
31028                   90.0                90.0              90.0   
31029                   90.0                90.0              90.0   
31030                   90.0                90.0              90.0   
31031                   90.0                90.0              90.0   
31032                   90.0                90.0              90.0   

       Knee_Ground_Angle  Ankle_Ground_Angle           Label  
0                   90.0                90.0   Jumping Jacks  
1                   90.0                90.0   Jumping Jacks  
2                   90.0                90.0   Jumping Jacks  
3                   90.0                90.0   Jumping Jacks  
4                   90.0                90.0   Jumping Jacks  
...                  ...                 ...             ...  
31028               90.0               -90.0  Russian twists  
31029               90.0               -90.0  Russian twists  
31030               90.0               -90.0  Russian twists  
31031               90.0               -90.0  Russian twists  
31032               90.0               -90.0  Russian twists  

[31033 rows x 12 columns]

In [ ]:
le = LabelEncoder()

for column in df.columns:
    if df[column].dtype == type(object):
        df[column] = le.fit_transform(df[column])

X = df.drop('Label', axis=1)
y = df['Label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred, target_names=le.classes_)

print("Matriz de Confusão:\n", conf_matrix)
print("\nClassification Report:\n", class_report)

Matriz de Confusão:
 [[ 987   27    4    1   10]
 [  10 1278   32    5    4]
 [   6    5 1984    0    9]
 [   3    5    8  817    8]
 [  10   33    5   14  942]]

Classification Report:
                 precision    recall  f1-score   support

 Jumping Jacks       0.97      0.96      0.97      1029
      Pull ups       0.95      0.96      0.95      1329
      Push Ups       0.98      0.99      0.98      2004
Russian twists       0.98      0.97      0.97       841
        Squats       0.97      0.94      0.95      1004

      accuracy                           0.97      6207
     macro avg       0.97      0.96      0.97      6207
  weighted avg       0.97      0.97      0.97      6207



In [ ]:
df.head(5)

Side  Shoulder_Angle  Elbow_Angle   Hip_Angle  Knee_Angle  Ankle_Angle  \
0     0       10.639208   174.466813  174.785143  179.848140   179.419276   
1     0       10.590342   174.428706  174.765042  179.775215   179.386147   
2     0       10.546746   174.489431  174.785790  179.660017   179.333710   
3     0       10.487682   174.614913  174.759542  179.614223   179.313926   
4     0       10.412107   174.758503  174.737721  179.570564   179.298805   

   Shoulder_Ground_Angle  Elbow_Ground_Angle  Hip_Ground_Angle  \
0                   90.0                90.0              90.0   
1                   90.0                90.0              90.0   
2                   90.0                90.0              90.0   
3                   90.0                90.0              90.0   
4                   90.0                90.0              90.0   

   Knee_Ground_Angle  Ankle_Ground_Angle  Label  
0               90.0                90.0      0  
1               90.0                90.0      0  
2               90.0                90.0      0  
3               90.0                90.0      0  
4               90.0                90.0      0